FROM python:alpine


RUN apk add unzip wget gettext \
    && mkdir -p /mnt/Modules \
    && mkdir -p /mnt/cms-content \
    && pip install tqdm

COPY /install-modules.py .

COPY /install-theme.sh .

COPY /upload-assets.sh .

COPY /upload-assets.py .

COPY /install-theme.py .

COPY /install-scripts.py .

COPY /installer.py .