FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

# Install unzip wget python3
RUN apt-get update && apt-get install -y unzip
RUN apt-get update -qq && apt-get install -y wget
RUN apt-get update -qq && apt-get install -y python3
RUN apt-get install -y npm
RUN apt-get install -y git
RUN npm install gulp -g

WORKDIR /opt/virtocommerce/tools

COPY /install-modules.py .
COPY /build_theme.sh .