FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

# Install unzip wget python3
RUN apt-get update && apt-get install -y unzip
RUN apt-get update -qq && apt-get install -y wget
RUN apt-get update -qq && apt-get install -y python3

WORKDIR /opt/virtocommerce/platform

COPY /install-modules.py .

ENTRYPOINT ["python3", "install-modules.py"]