name: Build platform installer image

on:
    workflow_dispatch:
        inputs:
          tag:
            description: 'Image tag'
            required: false
            default: 'latest'
    push:
        branches: [ VP-4553 ]
        paths:
            - 'vc-platform-installer/**'

    pull_request:
        branches: [ dev ]
        paths:
            - 'vc-platform-installer/**'
  
jobs:
    build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish Docker Image
        shell: pwsh
        run: |
            $imageTag = "docker.pkg.github.com/$('${{ github.repository }}'.ToLower())/platform-installer:${{ github.event.inputs.tag }}"
            docker build ${{ github.workspace }}/vc-platform-installer --tag $imageTag
#            docker push $imageTag
