on:
    push:
        branches: [ master ]
        paths:
            - 'vc-platform-installer/**'

    pull_request:
        branches: [ master ]
        paths:
            - 'vc-platform-installer/**'
  
jobs:
    build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
        uses: azure/docker-login@v1
        with:
            login-server: docker.pkg.github.com
            username: $GITHUB_ACTOR
            password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Publish Docker Image
        shell: pwsh
        run: |
            $imageTag = "docker.pkg.github.com/$('${{ github.repository }}'.ToLower())/platform-installer:latest"
            docker build vc-platform-installer --tag $imageTag
            docker push $imageTag